project:
  type: website
  output-dir: docs #../docs/
  resources:
    - "webr-serviceworker.js"
    - "webr-worker.js"
    
website:
  title: "Gabriel I. Cook"
   # google-analytics: 
  # Add site-url (without trailing / at the end)
  site-url: "https://slicesofdata.github.io/slicesofdata.github.io"
  # Add description: 
  description: "Website for data visualization lab at Claremont McKenna College."

  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Courses
        #href: courses.qmd
        # links to all sites that are nested under slicesofdata.github.io 
        # 9seem to populate automatically)
        menu: 
          - text: Foundations of Data Science
            href: https://gabrielcook.xyz/fods24
          - text: Data Visualization (2023)
            href: https://gabrielcook.xyz/dataviz23
      #- text: Past Courses
      #  #href: courses.qmd
      #  menu: 
      #    - text: Data Visualization (2023)
      #      href: https://gabrielcook.xyz/dataviz23
               # href: https://gabrielcook.xyz/dataviz23  #courses/dv/dv.qmd
          #- text: Cognitive Psychology
            #href: courses.qmd #[Link](../courses/dv/page2.qmd)
      - href: lab.qmd
        text: Lab
      - href: pubs.qmd
        text: Pubs
      - href: dataviztools.qmd
        text: DataViz Tools
      - href: CV/0.gicCV_newest.pdf
        text: CV
    right:
      - icon: github
        href: https://github.com/slicesofdata
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-cook-b618847/
        aria-label: LinkedIn
      #- icon: orcid
      - text: ORCID
        href: https://orcid.org/0000-0002-1921-5082
      - text: Instagram
        href: https://instagram.com/sowingchange

format:
  html:
    theme:  styles.scss
     # light: darkly
     # dark: darkly
    #css: styles.css
    page-layout: full
    toc: true

